### ISSUE TITLE
[ENHANCEMENT] Closing windows doesn't offer users a save option

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/journal#44]
When closing a journal window, have it check to see if any are unsaved and prompt the user for each one to see if they want it saved before the window is closed and changes lost (see gedit code for example, though theres doesn't actually close it after you save the item strangely).

**Comment by ryanleesipes** [comment]
Lol. This should be easy considering I already have the code for when you
close an unsaved tab.

**Comment by Justinzobel** [comment]
Fixed in https://github.com/solus-project/journal/pull/71
