### ISSUE TITLE
Problems with tabs when dragging out of the window.

### ISSUE THREAD

**Issue by cybre** [solus-project/journal#50]
So, let's do this in steps:
1. Open a second tab (with "Always show tabs" disabled)
2. Drag one of the tabs out of the window.
You can see that in both of the windows, the single tab is visible.
Same thing happens when attaching tabs, too.

**Comment by ryanleesipes** [comment]
Yes, I knew about this one. Was thinking about if I wanted to expose the one tab in the event that the user wanted to move it back.

**Comment by ryanleesipes** [comment]
@cybre I assume you would prefer it not be exposed?

**Comment by cybre** [comment]
I'm not sure. It does look weird but usability-wise, leaving it visible
makes sense.

**Comment by cybre** [comment]
One thing I would change is: when dragging out the last tab ("Always show
tabs" enabled), close the window. Currently, dragging out the last tab
leaves a notebook-less window open.

**Comment by ryanleesipes** [comment]
That is a good idea @cybre - I will see if I can do that.

**Comment by ryanleesipes** [comment]
Marking this closed as I think current behavior is pretty good.
