### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by boghison** [solus-project/journal#58]
Code is inconsistent, uses EvolveTab (to be renamed to SolusTab) etc. instead of JournalTab etc. Tabs and spaces are mixed.

**Comment by ryanleesipes** [comment]
@boghison I think this was handled in your pull request, is that correct? Feel free to make any future pull requests, I haven't had as much time to work on things lately. But if you want to work on anything or have questions just let me know.

**Comment by boghison** [comment]
@ryanleesipes no, not all of it, but if I have time I'll definitely look into improving the code readability :)

**Comment by ryanleesipes** [comment]
Much of this has been fixed in clean-ups. Will continue to do work to make this better.
