### ISSUE TITLE
Unable to change tab width

### ISSUE THREAD

**Issue by funnylookinhat** [solus-project/journal#59]
8 characters is an awful wide tab for some of us...  adding the ability to set it to 4 or 2 characters would be nice.  The ability for the "tab" key to actually insert spaces instead of tabs would be nice too.

**Comment by zesterer** [comment]
Defaulting to 4 characters in width would be nice.

**Comment by ikeydoherty** [comment]
GtkSourceView supports all of these things.. and more! ^^

**Comment by Justinzobel** [comment]
Moar? :D

**Comment by zesterer** [comment]
Yes, Moar!

On 15 April 2015 at 00:17, Justin <notifications@github.com> wrote:

> Moar? :D
>
> On Wed, 15 Apr 2015 at 01:27 Ikey Doherty <notifications@github.com>
> wrote:
>
> > GtkSourceView supports all of these things.. and more! ^^
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/solus-project/journal/issues/59#issuecomment-92929261>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/solus-project/journal/issues/59#issuecomment-93106714>
> .
>



-- 
Thanks,

Barry Smith

**Comment by ryanleesipes** [comment]
@zesterer Send me the pull request and I'll accept it. :)

**Comment by michaelrutherford** [comment]
Just added this feature in the 1.0.1 release of Journal.

**Comment by Justinzobel** [comment]
Fixed in 1.0.1, thanks @michaelrutherford
