### ISSUE TITLE
Add Edit Menu Option - Put "Indent" under there?

### ISSUE THREAD

**Issue by ryanleesipes** [solus-project/journal#69]
What do you guys think? Should we put Indent under an "Edit" menu option instead?

**Comment by michaelrutherford** [comment]
That sounds good to me. I'll go ahead and work on that as soon as I can.

**Comment by michaelrutherford** [comment]
My latest pull request addresses and corrects this issue.

**Comment by ryanleesipes** [comment]
Excellent.
