### ISSUE TITLE
Hide search in headerbar until called upon

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/journal#76]
It's a bit of an eyesore, should be hidden until needed. See evolve-sc if you need to see code for having it show when needed.

**Comment by michaelrutherford** [comment]
Yeah, it was mainly there for debugging and testing the search function. I'll take it down as soon as I can.

**Comment by Justinzobel** [comment]
No rush @michaelrutherford all good, great work so far.

**Comment by michaelrutherford** [comment]
This issue was fixed in the last commit.

**Comment by Justinzobel** [comment]
Awesome cheers Michael!
